name: Test

on:
  #push:
  # branches:
  #- main
  #- release/*
  workflow_dispatch:
    inputs:
      branch:
        description: "Define branch name"
        required: true
        default: "main"
      environment:
        description: "Container should be deployed to"
        type: environment
        required: true

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
